name: ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Set up node modules
      run: npm ci

    - name: Execute tests
      run: npm run test

    - name: Build artifacts
      run: npm run build